; =============================================================================
; SUPERPLAY - Waveform Patch for TRS-80 Color Computer Extended BASIC
; Originally by Jeremy Spiller, June 1988 (The Rainbow magazine)
;
; This program patches the Extended BASIC ROM to add waveform support to the
; PLAY command. It works by:
; 1. Copying the ROM into RAM in the upper 32K memory bank (if not already done).
; 2. Patching the PLAY command parser to support a new 'W' (Waveform) command.
; 3. Replacing the standard 6-bit DAC sound generation loop with a high-speed
;    Direct Digital Synthesis (DDS) engine that supports custom waveforms.
;
; The waveforms and a custom pitch table are generated by the BASIC loader
; and then moved into the upper RAM bank at $FA80.
; =============================================================================

		org	$7B7D

; -----------------------------------------------------------------------------
; LOADER / INSTALLER
; -----------------------------------------------------------------------------
; This section runs once when EXEC is called from BASIC.
; It prepares the system and installs the patches.

Start		lda	#$fb		; Default waveform page (Waveform 1)
		sta	$f9		; $f9 is an unused variable in BASIC Direct Page

; Test if upper RAM bank is writeable (is ROM already copied to RAM?)
		lda	$fa80		; Read byte from upper memory
		coma			; Complement it
		sta	$fa80		; Try to write it back
		cmpa	$fa80		; Did it stick?
		beq	CopyChunks	; If yes, RAM is already active, skip copy

; Copy ROM ($8000-$FA7F) to upper RAM
		orcc	#$50		; Disable interrupts
		ldx	#$8000		; Start of ROM
CopyROM		clr	$ffde		; Switch to ROM bank (SAM TY register)
		ldd	,x		; Read two bytes from ROM
		clr	$ffdf		; Switch to RAM bank
		std	,x++		; Write two bytes to RAM
		cmpx	#$fa80		; Done up to $FA80?
		bcs	CopyROM		; Loop until finished
		andcc	#$af		; Re-enable interrupts

; Copy code/data chunks to their destination in the BASIC interpreter
CopyChunks	leau	ChunkList,pcr	; Pointer to list of chunks
NextChunk	leax	Start,pcr	; Base address for relative offsets
		ldd	,u++		; Get source offset
		beq	Done		; If offset is 0, we are finished
		leax	d,x		; X = Source address
		ldy	,u++		; Y = Destination address (in RAM-patched ROM)
		ldd	,u++		; D = Number of bytes to copy
CopyLoop	pshs	a		; Preserve count high byte
		lda	,x+		; Read byte from source
		sta	,y+		; Write byte to destination
		puls	a		; Restore count high byte
		subd	#$0001		; Decrement count
		bne	CopyLoop	; Loop until chunk is moved
		bra	NextChunk	; Move to next chunk

Done		rts

; -----------------------------------------------------------------------------
; CHUNK DEFINITIONS
; -----------------------------------------------------------------------------
ChunkList	fdb	$0062, $9A6D, $001B ; Chunk 1: 'V'/'W' parser
		fdb	$007D, $9AC7, $0024 ; Chunk 2: 'P' parser & 'W' helper
		fdb	$00A1, $9B29, $0062 ; Chunk 3: DDS Sound Engine
		fdb	$0103, $FA80, $0380 ; Chunk 4: Pitch & Waveform tables
		fdb	$0000               ; End of list

; -----------------------------------------------------------------------------
; CHUNK 1: PARSER PATCH (Destination: $9A6D)
; -----------------------------------------------------------------------------
; Replaces the volume handling code. Adds detection for 'W' command.
; Original ROM at $9A6D handled 'V' only.

Patch_VW	cmpa	#'W		; Is it the new 'W' (Waveform) command?
		beq	Jump_W		; Yes, branch to 'W' handler
		cmpa	#'V		; Is it the 'V' (Volume) command?
		bne	BackToROM	; No, return to ROM to check other commands
		bsr	ParseNum	; Call numeric parser (defined in Chunk 2)
		cmpb	#$1f		; Limit volume to 0-31
		bhi	FC_Error	; Error if > 31
		stb	$df		; Store in VOLHI ($DF)
		aslb			; Scale volume for the DDS engine
		aslb
		aslb
		orb	#$07		; Set PIA sound enable bits
		sta	$e0		; Store in modified volume register ($E0)
		rts

Jump_W		jmp	Handler_W	; Jump to 'W' handler (in Chunk 2)
BackToROM	jmp	$9A8B		; Return to ROM parser loop

; -----------------------------------------------------------------------------
; CHUNK 2: PAUSE & WAVEFORM HANDLER (Destination: $9AC7)
; -----------------------------------------------------------------------------
; Replaces the 'P' (Pause) handler and provides helper routines.

Patch_P		jsr	$9ccb		; ROM: Evaluate numeric value in string
		tstb			; Check if 0
		bne	DoPause		; If > 0, proceed
FC_Error	jmp	$b44a		; ROM: Generate ?FC ERROR

DoPause		lda	$e2		; Get current Tempo ($E2)
		mul			; D = Duration * Tempo
		std	$d5		; Store in duration register ($D5)
		clr	$fd		; Set pitch to 0 (silence)
		clr	$fe
		jmp	SoundLoop	; Jump to our new sound engine

; 'W' Command Handler
Handler_W	jsr	$9ccb		; ROM: Parse waveform number (1, 2, or 3)
		decb			; Convert to 0, 1, or 2
		cmpb	#$02		; Valid range?
		bls	SetWave		; Yes
		bra	FC_Error	; No

SetWave		addb	#$fb		; Convert to page number ($FB, $FC, or $FD)
		stb	$f9		; Store in current waveform variable
		rts

; -----------------------------------------------------------------------------
; CHUNK 3: DDS SOUND ENGINE (Destination: $9B29)
; -----------------------------------------------------------------------------
; This replaces the standard note-to-frequency and sound generation logic.
; It uses Direct Digital Synthesis to play back waveforms.

SoundLoop	lda	$de		; Get current octave/note index?
		ldb	#12		; 12 semitones per octave
		clr	$ff40		; Hardware: sound/motor control
		mul			; Calculate base note
		addb	,s		; Add note within octave (from stack)
		aslb			; Double for word-sized pitch table
		ldx	#$fa80		; Point to Pitch Table in upper RAM
		ldd	b,x		; Load frequency increment (pitch)
		std	$fd		; Store in phase increment register
		ldb	$f9		; Get current waveform page
		stb	$fa		; Store in indirect pointer high byte

		ldd	$e1		; Load NOTELN ($E1) and TEMPO ($E2)
		mul			; Calculate raw duration
		std	$d5		; Store raw duration
		bsr	$9b8c		; ROM: Adjust for dotted notes (uses D)
		std	$e3		; Store adjusted duration in timer

		ldx	#$00ab		; Inner loop sample count
		tfr	x,y		; Keep copy in Y
		ldu	#$ffff		; System timer accumulator
		orcc	#$50		; Disable interrupts for clean sound

; Main DDS Synthesis Loop
SampleLoop	exg	a,a		; Timing delays for consistent sample rate
		exg	a,a
		exg	a,a
		exg	a,a
		lda	[$00fa]		; Load sample from [waveform_page, phase]
		ldb	$e0		; Load current volume
		mul			; Apply volume
		ora	#$03		; Maintain PIA bits
		sta	$ff20		; Output to 6-bit DAC
		ldd	$fb		; Load current phase accumulator
		addd	$fd		; Add frequency increment
		std	$fb		; Update phase
		leax	-1,x		; Decrement inner loop
		bne	SampleLoop	; Loop for a block of samples

		tfr	y,x		; Reset inner loop counter
		leau	1,u		; Increment system timer tracker
		nop			; Timing alignment
		ldd	$e3		; Get remaining duration
		subd	$d5		; Subtract block duration
		std	$e3		; Update timer
		bhi	SampleLoop	; Continue until note finishes

; Cleanup and update system clock
		ldd	$0112		; Get system timer
		leau	d,u		; Add our elapsed time
		stu	$0112		; Store updated timer
		ldd	#$0000		; Reset timer register
		std	$e3
		rts

; -----------------------------------------------------------------------------
; DATA NOTES
; -----------------------------------------------------------------------------
; The Pitch Table and Waveform data are not stored in the machine language 
; source. They are generated by the BASIC program at $7C80 and moved to $FA80 
; by the installer.
;
; $FA80: Pitch Table (122 bytes, 61 notes)
; $FB00: Waveform 1 (256 bytes)
; $FC00: Waveform 2 (256 bytes)
; $FD00: Waveform 3 (256 bytes)
